title:              Ground Station Alpha
email:              hmdsamarasekara@gmail.com
description:        EXPLORE-DIY-INNOVATE
author:             hmdsamarasekara
baseurl:            ""
url:                "https://hmdsamarasekara.github.io"

# Social Profiles
twitter_username:   hmdsamarasekara
github_username:    hmdsamarasekara
facebook_username:  dilusha.samarasekara.3

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
